### ISSUE TITLE
Automate the fitbit API calls in Heroku

### ISSUE THREAD

**Issue by nuclear-octopus** [nuclear-octopus/courier#62]
Why
Right now, I can only run the Fitbit API calls locally. This will not work long-term because it doesn't make sense to have to manually pull the data regularly.

How
- Explore if it's possible to automate the API calls through Heroku using the existing fitbit library
- If it isn't, look for another library that can do that
- Worst case scenario, build a new connection to the API that can accomplish what I need.

**Comment by SteamedHams722** [comment]
This is valuable. It shows how to get the app working on Heroku using flask: https://github.com/Stasonis/fitbit-api-example-python

**Comment by SteamedHams722** [comment]
This may be more helpful since it will allow me to keep using the existing fitbit library with cherrypy rather than use a whole new repository:

https://github.com/mispy/cherrypy-heroku-example/blob/master/app.py

**Comment by SteamedHams722** [comment]
Going to use oauth lib instead:
https://requests-oauthlib.readthedocs.io/en/latest/examples/real_world_example_with_refresh.html"""

**Comment by SteamedHams722** [comment]
Check out this repo. It has a solution for storing the tokens produced by orcasgit's gather keys script: https://github.com/davgibbs/fitbit-collect
